<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScreeningRepository\ScreeningRepository.csproj" />
    <ProjectReference Include="..\ScreeningUnitTestProject\ScreeningUnitTestProject.csproj" />
  </ItemGroup>

</Project>
